#!/usr/bin/env bash
# Concatenate 001 + 002 + 003 into one paste-ready file.
#
# WHY: the Supabase SQL editor is a single text box, and running three files in
# order by hand is three chances to run them out of order — which matters,
# because 003's RLS and purge function name tables that 001 and 002 create. One
# file can only run in the right order.
#
#   ./bundle.sh                     # writes _bundle.generated.sql
#   ./bundle.sh --stdout | pbcopy   # straight to the clipboard, nothing written
#
# Re-runnable: everything inside is `if not exists` / `create or replace`, so
# pasting the bundle a second time is a no-op that also catches up any column
# added to 002 since the first run (see its "Later column additions" block).
set -euo pipefail

cd "$(dirname "$0")"

FILES=(001_identity_and_entitlements.sql 002_encrypted_content.sql 003_rls_and_purge.sql)

emit() {
  echo "-- ============================================================"
  echo "-- Modwiz Supabase migration — generated bundle"
  echo "-- Generated $(date -u '+%Y-%m-%d %H:%M UTC') by sql/supabase-migration/bundle.sh"
  echo "--"
  echo "-- Do not edit this file. Edit the numbered source files and re-run."
  echo "-- Paste the whole thing into the Supabase SQL editor and Run."
  echo "-- ============================================================"
  echo
  for f in "${FILES[@]}"; do
    echo
    echo "-- >>>>>>>>>>>>>>>>>>>> $f >>>>>>>>>>>>>>>>>>>>"
    echo
    cat "$f"
    echo
  done
}

# An explicit flag rather than checking whether stdout is a terminal: that check
# reads as convenient and then behaves differently the first time this runs under
# a wrapper, a CI step, or a captured shell — where it would quietly print 700
# lines of SQL instead of writing the file it says it writes.
if [ "${1:-}" = "--stdout" ]; then
  emit
else
  emit > _bundle.generated.sql
  echo "Wrote _bundle.generated.sql ($(wc -l < _bundle.generated.sql | tr -d ' ') lines)."
  echo "Open it, copy all, paste into the Supabase SQL editor, Run."
fi
