-- Pojok Literasi — the article shelf and what each reader did with it.
-- Paste this once into the Supabase SQL editor (this repo has no migration
-- runner, see lib/supabase.js). Safe to re-run: the article rows are
-- upserted, so a corrected script replaces the text without touching reads.
--
-- WHY ARTICLES ARE A TABLE AND NOT CONSTANTS. Oracle's brief (PROMPT-pojok-
-- literasi.md §7) shipped them as JS by OTA. Rheza, 9 Okt 2026: a posting
-- panel is coming later, and until then he sends scripts by chat. A table
-- means a new article is a row, not a build — and the panel, when it comes,
-- writes to this same table. The 69 v0 scripts below come from
-- pojok-literasi-konten-v0.md (modwiz-app root) word for word; the parser that
-- produced them never retypes a sentence.
--
-- ACCESS IS DECIDED HERE, NOT IN THE APP. The Edge Function (supabase/
-- functions/literasi) serves a locked article as its first slide only, unless
-- the caller has unlocked it (user_unlocks, product_id 'literasi:<id>') or
-- is_privilege() says yes. The app never holds text it may not show.

create table if not exists literasi_articles (
  id           text primary key,            -- 'R-04': category letter + number, the script's own ids
  category     text not null,               -- featured | tutorial | realitas | mandala | jurnal | audio
  title        text not null,
  access       text not null default 'free',-- 'free' | 'souls'
  price        integer,                     -- 5 or 10 when access = 'souls' (LITERASI_PRICE standard / deep)
  source       text,                        -- Oracle's provenance line; never shown to readers
  slides       jsonb not null,              -- [{kind:'hook'|'wow'|'aha'|'coba'|'cta', text, cta?:{label}}]
  slug         text,                        -- public address: modwizmastery.com/literasi/<slug> (sql/literasi-v2.sql fills it)
  slides_v2    jsonb,                       -- reader-v2 script {lead, accent, long, slides}; null = old reader
  featured     boolean not null default false,
  status       text not null default 'published', -- 'draft' | 'published'
  sort         integer not null default 0,  -- shelf order inside a category
  published_at timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists literasi_articles_shelf_idx on literasi_articles (status, category, sort);
alter table literasi_articles enable row level security;

-- One row per (reader, article): read, bookmarked, liked, shared — four facts
-- about one pairing, so one table rather than the brief's three. A column
-- that is null simply has not happened yet.
create table if not exists literasi_user_articles (
  wp_user_id    bigint not null,
  article_id    text not null references literasi_articles (id),
  read_at       timestamptz,                -- first time the CTA slide was reached
  bookmarked_at timestamptz,
  liked_at      timestamptz,
  shared_at     timestamptz,
  updated_at    timestamptz not null default now(),
  primary key (wp_user_id, article_id)
);
create index if not exists literasi_user_articles_user_idx on literasi_user_articles (wp_user_id);
create index if not exists literasi_user_articles_article_idx on literasi_user_articles (article_id);
alter table literasi_user_articles enable row level security;

-- The counters under the reader's buttons (Rheza, 9 Okt: every button shows a
-- number). Counted on read; the shelf is small enough that a view is fine.
-- security_invoker: the view reads with the CALLER's rights, not its creator's
-- (Supabase advisor 'Security Definer View', 9 Okt 2026). The Edge Function
-- reads it with the service role either way; this only closes the hole for
-- anyone else who could reach the view.
create or replace view literasi_article_counts with (security_invoker = on) as
  select article_id,
         count(liked_at)      as likes,
         count(bookmarked_at) as bookmarks,
         count(shared_at)     as shares,
         count(read_at)       as reads
  from literasi_user_articles
  group by article_id;

insert into literasi_articles (id, category, title, access, price, source, slides, featured, sort, published_at) values
  ($q$F-01$q$, $q$featured$q$, $q$Selamat datang di Pojok Literasi$q$, $q$free$q$, null, $q$APP$q$, $q$[{"kind":"hook","text":"Ini bukan blog. Ini kotak kecil berisi satu pemahaman yang bisa kamu habiskan sambil menunggu pesanan datang."},{"kind":"wow","text":"Tiap artikel di sini selesai dalam 60–90 detik. Tidak ada iklan, tidak ada komentar, tidak ada gulir tanpa ujung. Habis ya habis."},{"kind":"aha","text":"Yang membuat orang berubah bukan banyaknya bacaan, melainkan satu kalimat yang pas, dibaca pada saat yang pas. Pojok ini dirancang untuk kalimat semacam itu."},{"kind":"coba","text":"Ketuk tanda pita pada artikel yang mengena. Ia menunggumu di tab Bookmarks."},{"kind":"cta","text":"artikel pertamanya soal sehelai gaun yang membelah internet.","cta":{"label":"Mulai dari rak Tentang Realitas"}}]$q$::jsonb, true, 0, '2026-10-09 09:00+07'),
  ($q$F-02$q$, $q$featured$q$, $q$Modwiz itu apa, sebenarnya$q$, $q$free$q$, null, $q$Modwiz Codex$q$, $q$[{"kind":"hook","text":"Bukan aplikasi motivasi. Bukan pula aplikasi meditasi. Lalu apa?"},{"kind":"wow","text":"Dua kata yang memegang semuanya: realitas dan keajaiban. Bagaimana manusia membentuk kenyataan yang ia inginkan, dan bagaimana ia kembali merasakan takjub di dalamnya."},{"kind":"aha","text":"Kebanyakan aplikasi memberimu alat. Modwiz berangkat dari keyakinan bahwa alatnya sudah ada di dalam dirimu, dan yang terjadi selama ini adalah sumbatan, bukan kekurangan."},{"kind":"cta","text":"tiga alat untuk membaca apa yang selama ini sudah bekerja untukmu.","cta":{"label":"Buka Ruang Mandala"}}]$q$::jsonb, true, 1, '2026-10-01 09:00+07'),
  ($q$F-03$q$, $q$featured$q$, $q$Dari pendobrak perdukunan ke pemberi keajaiban$q$, $q$free$q$, null, $q$Modwiz Origin Story · ULP bab Fundamental Forces$q$, $q$[{"kind":"hook","text":"Sebelum Modwiz ada, pendirinya dikenal publik karena satu hal: membongkar praktik perdukunan di televisi."},{"kind":"wow","text":"Bertahun-tahun ia membuktikan trik di balik \"keajaiban\" palsu. Lalu ia menemukan sesuatu yang lebih mengganggu: orang-orang tetap datang ke dukun, karena mereka memang membutuhkan rasa ajaib itu."},{"kind":"aha","text":"Masalahnya bukan pada kebutuhan akan keajaiban. Masalahnya pada siapa yang mengisinya. Maka keputusannya: berikan keajaiban yang asli, yang bisa dijelaskan, yang bekerja tanpa kemenyan dan tanpa tumbal."},{"kind":"cta","text":"","cta":{"label":"Baca \"Tiga hal yang tidak akan kami lakukan padamu\""}}]$q$::jsonb, true, 2, '2026-10-01 09:00+07'),
  ($q$F-04$q$, $q$featured$q$, $q$Merlin bukan chatbot$q$, $q$free$q$, null, $q$APP (Merlin)$q$, $q$[{"kind":"hook","text":"Kamu bisa bertanya apa saja pada Merlin. Tetapi bukan itu gunanya."},{"kind":"wow","text":"Merlin membaca seluruh perjalananmu di aplikasi ini: check-in pagi, catatan malam, hasil Mandala, goal yang kamu tulis dan lupakan. Lalu ia menyebutkan pola yang tidak kamu lihat sendiri."},{"kind":"aha","text":"Chatbot menjawab pertanyaanmu. Merlin menjawab pertanyaan yang belum sempat kamu ajukan. Karena itu ia tidak punya wajah: ia bukan tokoh utama cerita ini. Kamu yang utama."},{"kind":"cta","text":"mulai dengan satu kalimat jujur tentang harimu.","cta":{"label":"Bicara dengan Merlin"}}]$q$::jsonb, true, 3, '2026-10-01 09:00+07'),
  ($q$F-05$q$, $q$featured$q$, $q$Tiga hal yang tidak akan kami lakukan padamu$q$, $q$free$q$, null, $q$Modwiz Constitution$q$, $q$[{"kind":"hook","text":"Sebelum kamu percaya pada aplikasi ini, kamu berhak tahu batasnya."},{"kind":"wow","text":"Satu, Modwiz bekerja apa pun keyakinanmu. Pengguna yang taat beribadah tetap taat setelah memakainya. Dua, Modwiz tidak menjanjikan hasil. Tiga, Modwiz tidak pernah mengambil alih kemudi hidupmu; ia menemani, bukan memutuskan."},{"kind":"aha","text":"Aplikasi yang menjanjikan \"lakukan ini, dapatkan itu\" sedang menjual hal yang sama dengan dukun. Bedanya cuma kemasan. Kami memilih tidak ikut."},{"kind":"cta","text":"buka artikel \"Merlin bukan chatbot\".","cta":{"label":"Lihat bagaimana Merlin membaca, bukan meramal"}}]$q$::jsonb, true, 4, '2026-10-01 09:00+07'),
  ($q$F-06$q$, $q$featured$q$, $q$Seribu gelang, satu pertanyaan$q$, $q$free$q$, null, $q$AB 1.1, 3.2 · Awesome Bracelet$q$, $q$[{"kind":"hook","text":"Lebih dari seribu gelang pernah dikirim ke seluruh Indonesia. Pertanyaannya bukan \"apakah gelangnya bekerja\"."},{"kind":"wow","text":"Pertanyaannya: kenapa orang yang sama, setelah memakai gelang itu dan menjalani ritual paginya, mulai mengirim cerita perubahan ke grup, tanpa diminta. Salah satunya masih mengirim kabar enam tahun kemudian."},{"kind":"aha","text":"Gelangnya pengingat. Yang bekerja adalah apa yang kamu lakukan setiap pagi saat jari menyentuhnya. Benda bisa dibeli; kebiasaan harus dijalani."},{"kind":"cta","text":"ritual pagi yang sama, kini ada di aplikasi.","cta":{"label":"Coba Modwiz Priming"}}]$q$::jsonb, true, 5, '2026-10-01 09:00+07'),
  ($q$F-07$q$, $q$featured$q$, $q$Souls: mata uang yang tidak bisa dibeli dengan uang saja$q$, $q$free$q$, null, $q$APP (Souls, streak)$q$, $q$[{"kind":"hook","text":"Kamu baru saja membayar artikel ini dengan Souls. Dari mana Souls itu datang?"},{"kind":"wow","text":"Souls bisa dibeli, benar. Tetapi Souls juga lahir dari hal yang tidak dijual: tiga hari berturut-turut menepati janji pada diri sendiri, tiga puluh hari, seratus hari."},{"kind":"aha","text":"Ada dua cara memiliki Souls: membelinya, atau menjadi orang yang memperolehnya. Aplikasi ini sengaja membuat cara kedua terasa lebih bangga."},{"kind":"cta","text":"tonggak berikutnya lebih dekat dari yang kamu kira.","cta":{"label":"Lihat streak-mu"}}]$q$::jsonb, true, 6, '2026-10-01 09:00+07'),
  ($q$F-08$q$, $q$featured$q$, $q$Modwiz Privilege, dibaca pelan$q$, $q$free$q$, null, $q$APP (Privilege)$q$, $q$[{"kind":"hook","text":"\"Privilege\" di sini bukan hak istimewa yang diberikan pada orang tertentu. Ia sesuatu yang kamu berikan pada dirimu sendiri."},{"kind":"wow","text":"Energy Merlin tiga kali lipat. Sesi kerja bersama yang lebih panjang. Ingatan Merlin yang lebih dalam tentangmu. Streak yang bisa dinyalakan kembali gratis sebulan sekali. Dan seluruh Pojok Literasi terbuka."},{"kind":"aha","text":"Hitung begini: harga sebulan setara segelas es teh sehari. Pertanyaannya bukan mahal atau murah, melainkan apakah kamu sedang serius dengan perjalananmu."},{"kind":"cta","text":"","cta":{"label":"Lihat isi Modwiz Privilege"}}]$q$::jsonb, true, 7, '2026-10-01 09:00+07'),
  ($q$F-09$q$, $q$featured$q$, $q$Tiga tahap, satu peta$q$, $q$free$q$, null, $q$APP (Goal Saya, Realitas Saya) · AB 2.3$q$, $q$[{"kind":"hook","text":"Setiap perjalanan di aplikasi ini berdiri di atas satu garis: dari tempatmu sekarang menuju tempat yang kamu inginkan."},{"kind":"wow","text":"Stage 1 adalah keadaanmu hari ini. Stage 3 adalah tujuanmu. Dan Stage 2, yang paling sering diabaikan orang, adalah satu syarat yang membuat Stage 3 mungkin terjadi. Semua ditulis dengan kata-katamu sendiri, bukan label dari kami."},{"kind":"aha","text":"Orang gagal bukan karena tujuannya salah, melainkan karena melompat dari 1 ke 3 tanpa pernah menyebut apa yang harus benar di tengah."},{"kind":"cta","text":"baca lagi Stage 2 yang kamu tulis.","cta":{"label":"Buka Goal Saya"}}]$q$::jsonb, true, 8, '2026-10-01 09:00+07'),
  ($q$F-10$q$, $q$featured$q$, $q$Surat untuk yang mulai di hari yang berat$q$, $q$free$q$, null, $q$APP (Ignite CALM, Manas) · riset alpha$q$, $q$[{"kind":"hook","text":"Separuh orang memasang aplikasi ini saat hidupnya sedang tidak baik-baik saja. Kalau kamu salah satunya, surat ini untukmu."},{"kind":"wow","text":"Kamu tidak perlu menulis goal besar hari ini. Kamu tidak perlu semangat. Ada satu sesi tiga menit bernama CALM yang hanya meminta dua hal: apa yang sedang kamu pikirkan, dan apa yang kamu cari."},{"kind":"aha","text":"Hari berat bukan waktu untuk membangun. Hari berat adalah waktu untuk tidak runtuh. Itu saja sudah kemajuan, dan aplikasi ini mencatatnya sebagai kemajuan."},{"kind":"cta","text":"","cta":{"label":"Mulai CALM, tiga menit"}}]$q$::jsonb, true, 9, '2026-10-01 09:00+07'),
  ($q$T-01$q$, $q$tutorial$q$, $q$Peta Modwiz dalam 60 detik$q$, $q$free$q$, null, $q$APP$q$, $q$[{"kind":"hook","text":"Lima pintu, satu bola di tengah. Ini petanya."},{"kind":"wow","text":"Home: ritual harimu dan satu kartu fokus. Courses: kelas yang kamu ikuti. Bola di tengah: Merlin. Eksplor Dirimu: Mandala, sesi, dan Pojok Literasi ini. Profile: akses, sertifikat, pengaturan."},{"kind":"aha","text":"Kamu tidak perlu membuka semuanya. Hari biasa cukup dua: Home untuk ritual, bola untuk Merlin. Sisanya menunggu sampai kamu membutuhkannya."},{"kind":"cta","text":"lihat kartu ritual yang sedang menunggumu.","cta":{"label":"Kembali ke Home"}}]$q$::jsonb, false, 10, '2026-10-09 09:00+07'),
  ($q$T-02$q$, $q$tutorial$q$, $q$Ritual pagi: suasana hati dan tiga goal$q$, $q$free$q$, null, $q$APP (check-in pagi)$q$, $q$[{"kind":"hook","text":"Dua menit setelah bangun, sebelum membuka pesan siapa pun."},{"kind":"wow","text":"Langkah satu: pilih yang paling dekat dengan perasaanmu pagi ini, satu ketukan. Langkah dua: tulis tiga goal untuk hari ini. Bukan sepuluh. Tiga."},{"kind":"aha","text":"Goal yang ditulis pagi hari bukan daftar pekerjaan. Ia arah. Malam nanti kamu akan mencentangnya, dan yang belum tercapai akan menunggumu di pagi berikutnya, bukan hilang."},{"kind":"cta","text":"","cta":{"label":"Mulai ritual pagi"}}]$q$::jsonb, false, 11, '2026-10-01 09:00+07'),
  ($q$T-03$q$, $q$tutorial$q$, $q$Bicara dengan Merlin: lima cara supaya jawabannya mengena$q$, $q$free$q$, null, $q$APP (Merlin)$q$, $q$[{"kind":"hook","text":"Merlin menjawab sebaik pertanyaanmu. Begini cara bertanya."},{"kind":"wow","text":"Satu, ceritakan kejadiannya, bukan kesimpulanmu. Dua, sebut perasaanmu dengan satu kata. Tiga, tanyakan \"pola apa yang kamu lihat\", bukan \"aku harus apa\". Empat, kalau jawabannya mengena, simpan ke Catatan. Lima, ritual harian tidak memakai Energy; obrolan bebas memakainya."},{"kind":"aha","text":"Merlin bukan mesin pencari. Semakin jujur bahanmu, semakin tajam bacaannya."},{"kind":"cta","text":"","cta":{"label":"Bicara dengan Merlin"}}]$q$::jsonb, false, 12, '2026-10-01 09:00+07'),
  ($q$T-04$q$, $q$tutorial$q$, $q$Energy dan Souls: kenapa tidak ada angka$q$, $q$free$q$, null, $q$APP (Energy, Souls)$q$, $q$[{"kind":"hook","text":"Kamu tidak akan menemukan angka Energy di layar. Itu disengaja."},{"kind":"wow","text":"Energy tampil sebagai bilah yang terisi, lalu berkurang setiap kali kamu mengobrol bebas dengan Merlin, dan terisi lagi setiap 16 jam. Ritual harian tidak memakainya. Satu Soul bisa ditukar menjadi sepuluh Energy tambahan."},{"kind":"aha","text":"Angka mengundang perhitungan. Bilah mengundang perasaan: masih cukup, atau sudah tipis. Kamu tidak sedang mengelola kuota; kamu sedang memilih kapan obrolan itu layak."},{"kind":"cta","text":"","cta":{"label":"Lihat Energy Merlin di Eksplor Dirimu"}}]$q$::jsonb, false, 13, '2026-10-01 09:00+07'),
  ($q$T-05$q$, $q$tutorial$q$, $q$Streak padam? Nyalakan Kembali$q$, $q$free$q$, null, $q$APP (streak relight)$q$, $q$[{"kind":"hook","text":"Satu hari terlewat tidak harus menghapus tiga puluh hari sebelumnya."},{"kind":"wow","text":"Ada jendela tiga hari. Di dalamnya, kamu bisa menyalakan kembali streak dengan lima Souls. Pemilik Modwiz Privilege mendapat satu kali gratis setiap bulan."},{"kind":"aha","text":"Streak bukan hukuman untuk hari yang gagal. Ia catatan untuk hari-hari yang berhasil. Satu lubang tidak membatalkan jalannya."},{"kind":"cta","text":"","cta":{"label":"Buka streak-mu"}}]$q$::jsonb, false, 14, '2026-10-01 09:00+07'),
  ($q$T-06$q$, $q$tutorial$q$, $q$Membaca Realitas Saya: garis, gelombang, dan bintang$q$, $q$free$q$, null, $q$APP (Realitas Saya)$q$, $q$[{"kind":"hook","text":"Grafik ini bukan nilai rapor. Begini cara membacanya."},{"kind":"wow","text":"Garis putus-putus yang naik adalah perjalananmu dari Stage 1 ke 3. Gelombang yang mengelilinginya adalah hari-harimu, dari angka Hati dan Logika yang kamu isi tiap malam. Bintang kecil muncul di hari yang berat tetapi kamu tetap menulis pelajarannya."},{"kind":"aha","text":"Gelombang yang turun bukan kemunduran. Ia ayunan biasa. Yang kamu jaga adalah garisnya, dan garis hanya bergerak kalau kamu hadir."},{"kind":"cta","text":"","cta":{"label":"Buka Realitas Saya"}}]$q$::jsonb, false, 15, '2026-10-01 09:00+07'),
  ($q$T-07$q$, $q$tutorial$q$, $q$Mandala: mulai dari mana, diulang kapan$q$, $q$free$q$, null, $q$APP (Mandala)$q$, $q$[{"kind":"hook","text":"Tiga alat, dan urutan yang disarankan."},{"kind":"wow","text":"Mulai dari Agni Chakti: 30 pilihan, sekitar lima menit, lalu Merlin membaca kecenderunganmu. Ulangi setelah tiga bulan, atau saat target-mu berganti. Manas bisa dijalankan kapan saja. Svadharma, jalani lagi setiap ada persimpangan baru."},{"kind":"aha","text":"Alat ini tidak mengukur siapa kamu selamanya. Ia memotret ke mana kamu condong sekarang. Karena itu ia diulang."},{"kind":"cta","text":"","cta":{"label":"Mulai Agni Chakti"}}]$q$::jsonb, false, 16, '2026-10-01 09:00+07'),
  ($q$T-08$q$, $q$tutorial$q$, $q$Course di HP: rak buku, sertifikat, lanjut di mana saja$q$, $q$free$q$, null, $q$APP (Courses, Rak Buku, Sertifikat)$q$, $q$[{"kind":"hook","text":"Kelas yang kamu beli di situs otomatis muncul di sini. Tanpa unduh ulang."},{"kind":"wow","text":"Tab Courses menyimpan semua kelasmu dan mengingat sampai mana kamu menonton. Modul PDF tersusun di Rak Buku. Sertifikat muncul di Profile begitu kelas tamat."},{"kind":"aha","text":"Kelas yang ditonton sepuluh menit tiap hari di perjalanan lebih sering selesai daripada yang ditunggu \"nanti kalau senggang\"."},{"kind":"cta","text":"","cta":{"label":"Buka Courses"}}]$q$::jsonb, false, 17, '2026-10-01 09:00+07'),
  ($q$T-09$q$, $q$tutorial$q$, $q$XP dan Leaderboard: tujuh sumber, satu tombol sembunyi$q$, $q$free$q$, null, $q$APP (XP, Leaderboard)$q$, $q$[{"kind":"hook","text":"Kamu tidak harus berlomba. Tetapi kalau mau, begini aturannya."},{"kind":"wow","text":"XP datang dari tujuh kegiatan, termasuk ritual dan check-in. Tiga teratas tiap minggu mendapat Souls. Kalau papan peringkat tidak cocok untukmu, ia bisa disembunyikan."},{"kind":"aha","text":"Angka di papan tidak mengukur siapa yang paling berubah. Ia hanya mengukur siapa yang paling sering hadir. Dan hadir, memang, adalah separuh pekerjaan."},{"kind":"cta","text":"","cta":{"label":"Lihat Leaderboard"}}]$q$::jsonb, false, 18, '2026-10-01 09:00+07'),
  ($q$T-10$q$, $q$tutorial$q$, $q$Kisah: ritual berbagi dalam tiga menit$q$, $q$free$q$, null, $q$APP (Kisah)$q$, $q$[{"kind":"hook","text":"Di kelas lama, berbagi adalah tugas, bukan permintaan. Di aplikasi ini, tempatnya bernama Kisah."},{"kind":"wow","text":"Satu kejadian nyata, apa yang kamu sadari, apa yang berubah. Tiga baris. Kamu memilih apa yang tampil di kartu, lalu membagikannya ke mana pun."},{"kind":"aha","text":"Menuliskan perubahan membuatnya nyata dua kali: sekali saat terjadi, sekali saat kamu mengakuinya."},{"kind":"cta","text":"","cta":{"label":"Tulis Kisah pertamamu"}}]$q$::jsonb, false, 19, '2026-10-01 09:00+07'),
  ($q$T-11$q$, $q$tutorial$q$, $q$Pengingat yang tidak mengganggu$q$, $q$free$q$, null, $q$APP (notifikasi)$q$, $q$[{"kind":"hook","text":"Notifikasi yang salah jam akan kamu matikan. Yang tepat jam akan kamu tunggu."},{"kind":"wow","text":"Jam pengingat ritual pagi, siang, dan malam bisa kamu geser sendiri. Pengingat belajar kelas pun bisa diatur jamnya."},{"kind":"aha","text":"Pengingat terbaik datang tepat sebelum kebiasaan lama mengambil alih. Taruh ia di sana."},{"kind":"cta","text":"","cta":{"label":"Atur jam pengingat"}}]$q$::jsonb, false, 20, '2026-10-01 09:00+07'),
  ($q$T-12$q$, $q$tutorial$q$, $q$Catatan Merlin dan Favorit: supaya yang mengena tidak hilang$q$, $q$free$q$, null, $q$APP (Catatan Merlin, Favorit, Bookmarks)$q$, $q$[{"kind":"hook","text":"Jawaban terbaik Merlin biasanya datang saat kamu sedang tidak siap mencatat."},{"kind":"wow","text":"Setiap jawaban bisa disimpan ke Catatan Merlin. Kutipan harian bisa difavoritkan. Artikel di Pojok ini bisa ditandai pita. Tiga tempat, satu tujuan: kamu tidak perlu mengingat, kamu tinggal kembali."},{"kind":"aha","text":"Pemahaman yang tidak disimpan akan kamu temukan lagi tiga bulan kemudian, seolah baru. Yang disimpan bisa kamu pakai besok pagi."},{"kind":"cta","text":"","cta":{"label":"Buka Catatan Merlin"}}]$q$::jsonb, false, 21, '2026-10-01 09:00+07'),
  ($q$R-01$q$, $q$realitas$q$, $q$Gaun itu biru-hitam atau putih-emas?$q$, $q$free$q$, null, $q$fenomena "the dress" (2015) · SUN 1.3$q$, $q$[{"kind":"hook","text":"Pada 2015 satu foto gaun membelah internet menjadi dua kubu yang sama-sama yakin."},{"kind":"wow","text":"Sebagian melihat biru dan hitam. Sebagian lagi putih dan emas. Foto yang sama, mata yang sama sehatnya. Yang berbeda: tebakan otak masing-masing tentang cahaya di ruangan itu."},{"kind":"aha","text":"Kamu tidak pernah melihat dunia. Kamu melihat tafsiran otakmu tentang dunia. Dan tafsiran bisa dilatih."},{"kind":"cta","text":"alat untuk mengenali dari bahan apa kamu merangkai dunia.","cta":{"label":"Buka Manas"}}]$q$::jsonb, false, 22, '2026-10-09 09:00+07'),
  ($q$R-02$q$, $q$realitas$q$, $q$Gorila yang tidak kamu lihat$q$, $q$free$q$, null, $q$eksperimen Simons & Chabris (1999)$q$, $q$[{"kind":"hook","text":"Dalam satu eksperimen terkenal, separuh orang gagal melihat seekor gorila yang berjalan melintasi layar."},{"kind":"wow","text":"Mereka diminta menghitung operan bola. Di tengah video, orang berkostum gorila lewat, berhenti, memukul dada, lalu pergi. Sekitar separuh penonton bersumpah tidak ada gorila."},{"kind":"aha","text":"Perhatian adalah sorot lampu, bukan lampu ruangan. Apa pun yang kamu fokuskan setiap pagi menentukan gorila mana yang kamu lihat, dan mana yang kamu lewatkan."},{"kind":"cta","text":"itu caramu memilih ke mana lampu diarahkan.","cta":{"label":"Tulis tiga goal pagimu"}}]$q$::jsonb, false, 23, '2026-10-01 09:00+07'),
  ($q$R-03$q$, $q$realitas$q$, $q$Yang kamu lihat, dengar, dan rasakan belum tentu fakta$q$, $q$free$q$, null, $q$SUN 1.1, 1.3$q$, $q$[{"kind":"hook","text":"Kalimat ini diucapkan seorang pesulap yang pekerjaannya membongkar penipuan."},{"kind":"wow","text":"Penipu tidak perlu menipu matamu. Cukup penampilan yang tampak suci, kata-kata yang tampak santun, dan satu klaim yang tidak bisa kamu periksa. Sisanya otakmu yang mengisi."},{"kind":"aha","text":"Ada prinsip tua: penjelasan paling sederhana biasanya yang paling benar. Sebelum percaya pada sesuatu yang ajaib, cari dulu penjelasan yang membosankan. Kalau tidak ada, barulah takjub."},{"kind":"cta","text":"","cta":{"label":"Baca \"Tiga ruangan: Delusi, Ilusi, Realita\""}}]$q$::jsonb, false, 24, '2026-10-01 09:00+07'),
  ($q$R-04$q$, $q$realitas$q$, $q$Tiga ruangan: Delusi, Ilusi, Realita$q$, $q$souls$q$, 5, $q$ULP · kerangka DIR$q$, $q$[{"kind":"hook","text":"Setiap keputusan besar dalam hidupmu dibuat di ruangan yang bukan ruang fakta."},{"kind":"wow","text":"Ruang Delusi: tempat gambaran masa depan yang kamu inginkan tinggal. Ruang Ilusi: tempat cerita yang kamu percayai tentang dirimu. Ruang Realita: tempat uang, waktu, dan tubuh. Orang biasa terjebak di satu ruangan. Yang lincah berpindah dalam sepersekian detik."},{"kind":"aha","text":"Delusi bukan penyakit. Ia bahan baku. Semua yang kini nyata pernah mulai sebagai bayangan di kepala seseorang yang berani memasuki ruang itu, lalu keluar membawa rencana."},{"kind":"cta","text":"Stage 3-mu ditulis di ruang Delusi. Stage 2 adalah pintunya ke Realita.","cta":{"label":"Buka Goal Saya"}}]$q$::jsonb, false, 25, '2026-10-01 09:00+07'),
  ($q$R-05$q$, $q$realitas$q$, $q$Fisik dan metafisik: dua lantai dari rumah yang sama$q$, $q$souls$q$, 5, $q$SPM 01 · TRK 01$q$, $q$[{"kind":"hook","text":"Kata \"metafisik\" membuat sebagian orang curiga. Padahal artinya sederhana: yang di luar fisik."},{"kind":"wow","text":"Fisik: semua yang bisa diukur. Tubuh, uang, jarak. Metafisik: semua yang menggerakkan tubuh untuk mengambil uang dan menempuh jarak. Keinginan, keyakinan, makna. Tidak ada yang mistis di situ."},{"kind":"aha","text":"Orang yang hanya mengurus lantai fisik akan sibuk tanpa arah. Yang hanya tinggal di lantai metafisik akan penuh arah tanpa bergerak. Perubahan terjadi di tangga di antara keduanya."},{"kind":"cta","text":"tiga goal adalah tangga itu.","cta":{"label":"Mulai ritual pagi"}}]$q$::jsonb, false, 26, '2026-10-01 09:00+07'),
  ($q$R-06$q$, $q$realitas$q$, $q$Kontraktor realita$q$, $q$souls$q$, 5, $q$AB 4.1$q$, $q$[{"kind":"hook","text":"Kalau hidupmu terasa sedang dibongkar, mungkin kamu sedang direnovasi."},{"kind":"wow","text":"Tidak ada rumah yang bisa diubah tanpa ada dinding yang dirobohkan, debu di mana-mana, dan beberapa minggu tidur di ruangan yang tidak nyaman. Perubahan realita bekerja persis seperti itu."},{"kind":"aha","text":"Ketidaknyamanan bukan tanda kamu salah jalan. Sering kali ia tanda pekerjaan sedang berlangsung. Pertanyaannya cuma satu: kamu kontraktornya, atau penghuni yang mengeluh?"},{"kind":"coba","text":"Tulis tiga hal baik di sekitarmu hari ini, dan satu perbedaan antara realitamu dulu dengan hari ini."},{"kind":"cta","text":"","cta":{"label":"Tulis di jurnal malam"}}]$q$::jsonb, false, 27, '2026-10-01 09:00+07'),
  ($q$R-07$q$, $q$realitas$q$, $q$Kalau semua uang di dunia dibagi rata$q$, $q$souls$q$, 5, $q$ULP bab Ultimate Learning Process$q$, $q$[{"kind":"hook","text":"Andai seluruh uang di dunia dikumpulkan lalu dibagi rata, apa yang terjadi lima tahun kemudian?"},{"kind":"wow","text":"Yang kaya kembali kaya, yang miskin kembali miskin. Bukan karena kecerdasan. Karena rasa \"wajar\". Orang Tiongkok wajar makan dengan sumpit; orang Indonesia wajar makan dengan tangan. Bukan lebih pintar, hanya terbiasa."},{"kind":"aha","text":"Realita yang kamu tinggali hari ini adalah realita yang terasa wajar bagimu. Untuk pindah, kamu tidak perlu lebih pintar. Kamu perlu membiasakan diri dengan yang belum wajar, sampai ia wajar."},{"kind":"cta","text":"kebiasaan dihitung dalam hari, bukan niat.","cta":{"label":"Lihat streak-mu"}}]$q$::jsonb, false, 28, '2026-10-01 09:00+07'),
  ($q$R-08$q$, $q$realitas$q$, $q$Kebutuhan mengalahkan seratus keinginan$q$, $q$souls$q$, 5, $q$ULP langkah 1$q$, $q$[{"kind":"hook","text":"Ingat sesuatu yang bertahun-tahun kamu inginkan, lalu tiba-tiba kamu dapatkan dalam waktu singkat?"},{"kind":"wow","text":"Biasanya ada satu perubahan kecil sebelumnya: keinginan itu berubah menjadi kebutuhan. Rumah yang \"ingin\" dibeli bertahun-tahun, dibeli dalam setahun begitu ia \"harus\"."},{"kind":"aha","text":"Satu kebutuhan jauh lebih kuat daripada seratus keinginan. Keahlian orang yang cepat mendapatkan sesuatu bukan berdoa lebih keras, melainkan menggeser \"ingin\" menjadi \"butuh\", dengan alasan yang jujur."},{"kind":"coba","text":"Ambil satu keinginanmu. Tulis tiga alasan kenapa kamu membutuhkannya, bukan sekadar menginginkannya."},{"kind":"cta","text":"","cta":{"label":"Buka Goal Saya"}}]$q$::jsonb, false, 29, '2026-10-01 09:00+07'),
  ($q$R-09$q$, $q$realitas$q$, $q$Lampu merah tidak pernah bilang "berhenti"$q$, $q$souls$q$, 5, $q$AB 2.2 (tentang Sygil)$q$, $q$[{"kind":"hook","text":"Tidak ada tulisan \"berhenti sampai hijau menyala\" di lampu lalu lintas. Tetapi kamu berhenti."},{"kind":"wow","text":"Kita hidup di antara simbol. Warna, bentuk, bunyi, yang diterjemahkan otak dalam sepersekian detik tanpa perlu kalimat. Itulah sebabnya kartu, gelang, atau satu kata di layar bisa mengarahkan tindakan."},{"kind":"aha","text":"Pertanyaannya bukan apakah kamu terpengaruh simbol. Kamu sudah. Pertanyaannya: simbol siapa yang mengisi harimu? Yang dipasang orang lain, atau yang kamu pilih sendiri?"},{"kind":"cta","text":"satu simbol yang kamu pilih sendiri, setiap pagi.","cta":{"label":"Lihat Fokusmu Hari Ini"}}]$q$::jsonb, false, 30, '2026-10-01 09:00+07'),
  ($q$R-10$q$, $q$realitas$q$, $q$Tiga keterampilan menyusuri realita$q$, $q$souls$q$, 5, $q$AB 4.2$q$, $q$[{"kind":"hook","text":"Saat perjalanan terasa berat, kebanyakan orang menambah kecepatan. Yang dibutuhkan justru tiga keterampilan lain."},{"kind":"wow","text":"Present: tarik napas, lihat sekeliling, sebutkan apa yang sudah kamu miliki. Peace: masa lalu hanyalah kejadian yang harus terjadi agar kamu sampai di sini. Believe: percayai masa depan yang sedang kamu bentuk, dan jangan mengubah keinginanmu tiap minggu."},{"kind":"aha","text":"Rumah tidak kunjung selesai kalau pemiliknya mengganti denah setiap kali debu beterbangan."},{"kind":"cta","text":"sesi tiga menit untuk Present.","cta":{"label":"Mulai CALM"}}]$q$::jsonb, false, 31, '2026-10-01 09:00+07'),
  ($q$R-11$q$, $q$realitas$q$, $q$Gila kalau berharap hasil berbeda dengan cara yang sama$q$, $q$souls$q$, 10, $q$AB 4.3, 5.1$q$, $q$[{"kind":"hook","text":"Realitamu tidak berubah? Ada tiga kemungkinan, dan ketiganya punya resep berbeda."},{"kind":"wow","text":"Tidak berubah sama sekali: butuh fokus dan energi lebih. Berubah tetapi tidak sesuai: butuh waktu lebih panjang. Berubah perlahan: teruskan. Yang tidak ada dalam daftar: mengulang hal yang sama, di tempat yang sama, dengan orang yang sama, lalu berharap beda."},{"kind":"aha","text":"Ada siklus yang bisa diduplikasi: potensi, tindakan, hasil, keyakinan, lalu kembali ke potensi yang lebih besar. Kebanyakan orang berhenti di hasil, karena hasilnya tidak seperti yang dibayangkan. Padahal hasil negatif dan positif sama-sama memutar siklusnya."},{"kind":"cta","text":"lihat di mana siklusmu biasanya berhenti.","cta":{"label":"Buka Realitas Saya"}}]$q$::jsonb, false, 32, '2026-10-01 09:00+07'),
  ($q$R-12$q$, $q$realitas$q$, $q$Kenapa setelah menulis goal kamu mulai melihatnya di mana-mana$q$, $q$souls$q$, 10, $q$fenomena frequency illusion · APP (Goal Saya)$q$, $q$[{"kind":"hook","text":"Pernah memutuskan membeli mobil tertentu, lalu tiba-tiba mobil itu ada di setiap jalan?"},{"kind":"wow","text":"Mobilnya tidak bertambah. Perhatianmu yang berubah. Fenomena ini punya nama dalam psikologi, dan ia terjadi pada apa pun yang baru saja kamu putuskan penting."},{"kind":"aha","text":"Menulis goal bukan ritual mistis. Ia cara memberi tahu sistem penyaring di kepalamu: mulai sekarang, yang ini penting. Setelah itu peluang terlihat, bukan karena ia muncul, melainkan karena kamu berhenti melewatkannya."},{"kind":"cta","text":"","cta":{"label":"Tulis ulang Stage 2-mu dalam satu kalimat"}}]$q$::jsonb, false, 33, '2026-10-01 09:00+07'),
  ($q$M-01$q$, $q$mandala$q$, $q$Ruang Mandala: tiga alat, satu pertanyaan$q$, $q$free$q$, null, $q$APP (Mandala)$q$, $q$[{"kind":"hook","text":"Tiga alat ini tidak menanyakan siapa kamu. Mereka menanyakan apa yang selama ini sudah bekerja untukmu."},{"kind":"wow","text":"Agni Chakti membaca kecenderungan tindakanmu. Manas membaca dari bahan indra apa kamu merangkai dunia. Svadharma membaca ke arah mana kamu sebenarnya menghadap."},{"kind":"aha","text":"Kebanyakan tes kepribadian memberimu label. Mandala memberimu bahan, lalu Merlin membacanya bersama catatan harianmu. Hasilnya bukan tipe, melainkan pola."},{"kind":"cta","text":"lima menit, 30 pilihan.","cta":{"label":"Mulai Agni Chakti"}}]$q$::jsonb, false, 34, '2026-10-01 09:00+07'),
  ($q$M-02$q$, $q$mandala$q$, $q$Kamu tidak diminta menebak kekuatanmu$q$, $q$free$q$, null, $q$Modwiz Constitution · AB 2.2$q$, $q$[{"kind":"hook","text":"Pertanyaan \"apa kelebihanmu?\" adalah pertanyaan paling sulit di dunia. Karena itu Mandala tidak menanyakannya."},{"kind":"wow","text":"Di kelas lama, orang diminta menulis sendiri kekuatannya. Hasilnya sering kosong atau ragu. Di sini kamu hanya memilih antara dua hal yang sama-sama sah. Merlin yang menyebutkan polanya."},{"kind":"aha","text":"Potensi adalah keluaran, bukan masukan. Orang jarang tahu kekuatannya karena ia terasa biasa saja. Yang terasa biasa bagimu, justru itu yang orang lain tidak bisa."},{"kind":"cta","text":"","cta":{"label":"Buka Ruang Mandala"}}]$q$::jsonb, false, 35, '2026-10-01 09:00+07'),
  ($q$M-03$q$, $q$mandala$q$, $q$Agni Chakti: 30 pilihan, tidak ada jawaban salah$q$, $q$free$q$, null, $q$APP (Agni Chakti)$q$, $q$[{"kind":"hook","text":"\"Melihat fakta\" atau \"melihat cerita di baliknya\"? Keduanya benar. Itu intinya."},{"kind":"wow","text":"Tiga puluh pasang pilihan. Setiap pasangnya sengaja dibuat sama-sama terhormat, supaya kamu tidak memilih yang \"terdengar lebih baik\", melainkan yang memang kamu. Dari sana terbaca empat kecenderungan bertindak."},{"kind":"aha","text":"Alat ini bukan tentang apa yang menyala dalam dirimu. Ia tentang apa yang sudah menyala, dan selama ini kamu anggap wajar."},{"kind":"cta","text":"","cta":{"label":"Mulai Agni Chakti"}}]$q$::jsonb, false, 36, '2026-10-01 09:00+07'),
  ($q$M-04$q$, $q$mandala$q$, $q$Manas: dari bahan apa kamu merangkai dunia$q$, $q$souls$q$, 5, $q$APP (Manas)$q$, $q$[{"kind":"hook","text":"Dua orang menonton film yang sama. Satu mengingat warnanya, satu mengingat dialognya. Keduanya menonton film yang berbeda."},{"kind":"wow","text":"Manas menamai bahan indra yang paling sering dipakai pikiranmu untuk menyusun pengalaman. Delapan belas pilihan dan enam tugas membayangkan. Tidak ada yang lebih baik; ada yang lebih kamu."},{"kind":"aha","text":"Begitu kamu tahu bahanmu, dua hal berubah: cara kamu belajar, dan cara kamu menjelaskan sesuatu pada orang yang bahannya berbeda."},{"kind":"cta","text":"","cta":{"label":"Mulai Manas"}}]$q$::jsonb, false, 37, '2026-10-01 09:00+07'),
  ($q$M-05$q$, $q$mandala$q$, $q$Svadharma: arah pulang terbaca dari yang kamu tolak lepaskan$q$, $q$souls$q$, 5, $q$APP (Svadharma)$q$, $q$[{"kind":"hook","text":"Kamu bisa berbohong tentang apa yang kamu inginkan. Sulit berbohong tentang apa yang tidak rela kamu lepaskan."},{"kind":"wow","text":"Delapan belas persimpangan. Di tiap persimpangan kamu harus merelakan satu hal. Dari pola yang kamu pertahankan, terbaca ke arah mana kamu sebenarnya menghadap, yang sering berbeda dari arah yang kamu ucapkan."},{"kind":"aha","text":"Svadharma menunjukkan arah. Ia tidak menyuruhmu lari. Pulang dimulai dengan tahu di mana rumahmu."},{"kind":"cta","text":"","cta":{"label":"Mulai Svadharma"}}]$q$::jsonb, false, 38, '2026-10-01 09:00+07'),
  ($q$M-06$q$, $q$mandala$q$, $q$Kenapa hasilnya bukan tipe kepribadian$q$, $q$souls$q$, 5, $q$Modwiz Constitution (prinsip silang-data instrumen) · efek Barnum (Forer, 1948)$q$, $q$[{"kind":"hook","text":"Pada 1948 seorang psikolog memberi mahasiswanya \"analisis kepribadian pribadi\". Semua mendapat teks yang sama persis. Rata-rata menilainya sangat akurat."},{"kind":"wow","text":"Kalimat seperti \"kamu butuh disukai, tetapi kadang kritis pada diri sendiri\" terasa pas untuk siapa saja. Itulah jebakan tes kepribadian: ia cocok karena ia umum."},{"kind":"aha","text":"Hasil Mandala tidak berdiri sendiri. Merlin menyilangkannya dengan apa yang benar-benar kamu lakukan di aplikasi ini: jam check-in, goal yang tercapai, catatan malammu. Pola yang muncul dari tindakanmu sendiri tidak bisa dipasang pada orang lain."},{"kind":"cta","text":"","cta":{"label":"Lihat hasil Mandala terakhirmu"}}]$q$::jsonb, false, 39, '2026-10-01 09:00+07'),
  ($q$M-07$q$, $q$mandala$q$, $q$Tiga bulan kemudian$q$, $q$souls$q$, 5, $q$APP (Agni Chakti, ulang)$q$, $q$[{"kind":"hook","text":"Agni Chakti memintamu kembali setelah tiga bulan. Bukan karena hasilnya kedaluwarsa."},{"kind":"wow","text":"Dalam tiga bulan, orang yang menjalani ritual harian biasanya bergeser. Bukan berubah total, bergeser. Alat ini dibuat untuk menangkap pergeseran itu, dan Merlin akan menyebut apa yang berbeda."},{"kind":"aha","text":"Hasil pertama adalah foto. Hasil kedua adalah film."},{"kind":"cta","text":"","cta":{"label":"Cek kapan Agni Chakti-mu bisa diulang"}}]$q$::jsonb, false, 40, '2026-10-01 09:00+07'),
  ($q$M-08$q$, $q$mandala$q$, $q$Cara membaca Pembacaan Merlin tanpa membela diri$q$, $q$souls$q$, 5, $q$APP (Pembacaan Merlin)$q$, $q$[{"kind":"hook","text":"Reaksi pertama pada bacaan yang tepat biasanya \"ah, tidak juga\"."},{"kind":"wow","text":"Coba tiga langkah ini. Baca sekali tanpa berhenti. Tutup. Besok pagi baca lagi, lalu tanya: di mana minggu ini aku melakukan persis seperti itu?"},{"kind":"aha","text":"Bacaan yang salah akan terasa asing. Bacaan yang benar akan terasa mengganggu. Yang mengganggu itulah yang berguna."},{"kind":"cta","text":"simpan satu kalimat yang paling mengganggu.","cta":{"label":"Buka Catatan Merlin"}}]$q$::jsonb, false, 41, '2026-10-01 09:00+07'),
  ($q$M-09$q$, $q$mandala$q$, $q$Kalau dua orang sama-sama memakai Manas$q$, $q$souls$q$, 5, $q$APP (Manas)$q$, $q$[{"kind":"hook","text":"Pertengkaran yang paling melelahkan sering bukan soal isi, melainkan soal bahan."},{"kind":"wow","text":"Satu orang menjelaskan dengan gambaran, yang lain menunggu kalimat yang jelas. Keduanya merasa tidak didengar. Begitu masing-masing tahu bahan indranya, percakapan yang sama berubah nada."},{"kind":"aha","text":"Memahami bahan orang lain bukan cara mengendalikannya. Ia cara berhenti saling melewatkan."},{"kind":"cta","text":"","cta":{"label":"Bagikan Manas ke satu orang terdekat"}}]$q$::jsonb, false, 42, '2026-10-01 09:00+07'),
  ($q$M-10$q$, $q$mandala$q$, $q$Pola yang tidak bisa kamu lihat sendiri$q$, $q$souls$q$, 10, $q$APP (Merlin membaca seluruh semesta)$q$, $q$[{"kind":"hook","text":"Ada hal tentang dirimu yang hanya bisa dilihat dari luar, dan bukan oleh orang lain."},{"kind":"wow","text":"Jam berapa kamu biasanya absen check-in. Goal jenis apa yang selalu tercentang, dan jenis apa yang selalu terbawa ke esok. Kata apa yang paling sering muncul di jurnal malammu. Kamu tidak mengingat ini. Merlin iya."},{"kind":"aha","text":"Kamu terlalu dekat dengan hidupmu untuk melihat polanya. Itu bukan kekurangan; itu jarak. Mandala dan catatan harian memberi Merlin jarak yang kamu tidak punya."},{"kind":"cta","text":"","cta":{"label":"Tanya Merlin: \"pola apa yang kamu lihat dari sebulan terakhir?\""}}]$q$::jsonb, false, 43, '2026-10-01 09:00+07'),
  ($q$M-11$q$, $q$mandala$q$, $q$Mandala dan Stage 2-mu$q$, $q$souls$q$, 10, $q$APP (Mandala, Goal Saya)$q$, $q$[{"kind":"hook","text":"Hasil Mandala yang tidak dipakai untuk apa-apa hanya jadi bacaan menarik. Begini cara memakainya."},{"kind":"wow","text":"Ambil Stage 2 yang kamu tulis, satu syarat yang membuat tujuanmu mungkin. Lalu baca hasil Agni Chakti-mu: kecenderungan mana yang membantu syarat itu, dan mana yang selama ini diam-diam menghambatnya?"},{"kind":"aha","text":"Alat tidak mengubah apa pun. Alat yang dipasangkan dengan satu goal yang jelas mengubah cara kamu mengambil langkah besok pagi."},{"kind":"cta","text":"","cta":{"label":"Buka Goal Saya, lalu Agni Chakti, berdampingan"}}]$q$::jsonb, false, 44, '2026-10-01 09:00+07'),
  ($q$J-01$q$, $q$jurnal$q$, $q$Tiga goal pagi: kenapa tiga, bukan sepuluh$q$, $q$free$q$, null, $q$APP (check-in pagi) · AB 2.4$q$, $q$[{"kind":"hook","text":"Daftar sepuluh tugas membuatmu merasa produktif pada pukul tujuh pagi dan gagal pada pukul sembilan malam."},{"kind":"wow","text":"Tiga goal adalah jumlah yang bisa diingat tanpa membuka aplikasi. Jumlah yang muat dalam satu hari yang ada kejutannya. Jumlah yang, kalau dua tercapai, tetap terasa menang."},{"kind":"aha","text":"Goal pagi bukan daftar kerja. Ia pernyataan tentang hari seperti apa yang kamu pilih. Daftar kerja tinggal di tempat lain."},{"kind":"cta","text":"","cta":{"label":"Tulis tiga goalmu"}}]$q$::jsonb, false, 45, '2026-10-09 09:00+07'),
  ($q$J-02$q$, $q$jurnal$q$, $q$Satu kemenangan kecil sebelum tidur$q$, $q$free$q$, null, $q$APP (ritual malam) · penelitian jurnal syukur (Emmons & McCullough, 2003)$q$, $q$[{"kind":"hook","text":"Otak tidak menyimpan harimu. Ia menyimpan rangkumannya. Dan rangkuman ditulis sebelum tidur."},{"kind":"wow","text":"Dalam penelitian yang banyak dikutip, orang yang menuliskan beberapa hal yang ia syukuri tiap malam melaporkan tidur lebih baik dan merasa lebih optimis dalam hitungan minggu, bukan tahun."},{"kind":"aha","text":"Satu kemenangan kecil yang ditulis mengalahkan sepuluh kemenangan yang tidak diakui. Bukan karena menulis itu ajaib, melainkan karena yang ditulis adalah yang diingat."},{"kind":"cta","text":"","cta":{"label":"Mulai ritual malam"}}]$q$::jsonb, false, 46, '2026-10-01 09:00+07'),
  ($q$J-03$q$, $q$jurnal$q$, $q$Hati dan Logika: dua angka yang jujur$q$, $q$free$q$, null, $q$APP (Realitas Saya)$q$, $q$[{"kind":"hook","text":"Tiap malam kamu diminta dua angka. Keduanya tentang hal yang sama, dari dua sisi yang jarang sepakat."},{"kind":"wow","text":"Hati: seberapa dekat hari ini terasa dengan tujuanmu. Logika: seberapa dekat keadaan nyatamu, uang, pekerjaan, jaringan, dengan tujuan itu. Jaraknya di antara keduanya adalah informasi."},{"kind":"aha","text":"Hati tinggi, Logika rendah: kamu sedang penuh harapan tanpa langkah. Logika tinggi, Hati rendah: kamu sedang maju tanpa merasakannya. Keduanya butuh resep berbeda, dan grafikmu akan menunjukkannya."},{"kind":"cta","text":"","cta":{"label":"Isi Hati dan Logika malam ini"}}]$q$::jsonb, false, 47, '2026-10-01 09:00+07'),
  ($q$J-04$q$, $q$jurnal$q$, $q$Kita adalah apa yang kita ulang$q$, $q$souls$q$, 5, $q$AB 2.4 (Ritual Card)$q$, $q$[{"kind":"hook","text":"Bukan apa yang kamu putuskan pada tahun baru. Apa yang kamu lakukan pada Selasa biasa."},{"kind":"wow","text":"Kartu ritual lama membagi hari menjadi tiga: pagi, saat bawah sadar paling terbuka; siang, saat realita dibentuk lewat tindakan biasa; malam, saat hari dinyatakan selesai dan esok diberi kisah baru."},{"kind":"aha","text":"Kebiasaan bukan hasil dari motivasi. Kebiasaan adalah pengganti motivasi, untuk hari-hari ketika motivasi tidak datang."},{"kind":"cta","text":"hitungan Selasa-Selasa biasa.","cta":{"label":"Lihat streak-mu"}}]$q$::jsonb, false, 48, '2026-10-01 09:00+07'),
  ($q$J-05$q$, $q$jurnal$q$, $q$Menulis rencana besok membuat tidur lebih nyenyak$q$, $q$souls$q$, 5, $q$AB 2.4 · penelitian Baumeister & Masicampo (2011)$q$, $q$[{"kind":"hook","text":"Pikiran yang berputar di tempat tidur hampir selalu tentang hal yang belum selesai."},{"kind":"wow","text":"Dalam satu rangkaian penelitian, orang yang menuliskan rencana untuk tugas yang belum selesai lebih jarang diganggu pikiran tentang tugas itu. Bukan menyelesaikannya. Cukup merencanakannya."},{"kind":"aha","text":"Otak menagih tugas yang menggantung sampai ia yakin tugas itu sudah dipegang. Kalimat \"besok pukul sembilan aku mengerjakan ini\" cukup untuk membuatnya melepaskan."},{"kind":"cta","text":"","cta":{"label":"Tulis prioritas besok di ritual malam"}}]$q$::jsonb, false, 49, '2026-10-01 09:00+07'),
  ($q$J-06$q$, $q$jurnal$q$, $q$Bintang di hari yang buruk$q$, $q$souls$q$, 5, $q$APP (turning point marker) · Ray Dalio$q$, $q$[{"kind":"hook","text":"Di grafik Realitas Saya ada bintang kecil. Ia hanya muncul pada hari yang berat."},{"kind":"wow","text":"Syaratnya dua: angka harimu rendah, dan kamu tetap menuliskan pelajarannya. Hari seperti itu ditandai, karena ada rumus yang diyakini banyak orang sukses: \"Pain + Reflection = Progress.\""},{"kind":"aha","text":"Hari buruk tanpa refleksi hanyalah hari buruk. Hari buruk dengan satu paragraf jujur adalah titik balik. Bintang itu bukan hiburan; ia catatan bahwa kamu tidak membuang rasa sakitnya."},{"kind":"cta","text":"cari bintangmu.","cta":{"label":"Buka Realitas Saya"}}]$q$::jsonb, false, 50, '2026-10-01 09:00+07'),
  ($q$J-07$q$, $q$jurnal$q$, $q$Bullish, Bearish, Sideways: membaca gelombang tanpa panik$q$, $q$souls$q$, 5, $q$APP (Realitas Saya)$q$, $q$[{"kind":"hook","text":"Grafikmu memakai bahasa pasar saham. Ada alasannya."},{"kind":"wow","text":"Bullish: gelombang jangka pendekmu sedang naik. Bearish: sedang turun. Sideways: datar. Ketiganya dihitung dari beberapa hari terakhir, dan tidak satu pun menilai perjalananmu secara keseluruhan."},{"kind":"aha","text":"Investor yang panik saat Bearish menjual di harga terendah. Yang paham siklus justru menanam. Gelombang turun di grafikmu adalah ayunan biasa; garis panjangnya yang kamu jaga."},{"kind":"cta","text":"","cta":{"label":"Lihat tren tujuh hari terakhirmu"}}]$q$::jsonb, false, 51, '2026-10-01 09:00+07'),
  ($q$J-08$q$, $q$jurnal$q$, $q$Goal yang terbawa ke esok$q$, $q$souls$q$, 5, $q$APP (The Handoff / carry-over)$q$, $q$[{"kind":"hook","text":"Dari tiga goal, biasanya satu atau dua tidak tercentang. Itu normal. Yang penting apa yang terjadi besoknya."},{"kind":"wow","text":"Goal yang belum tercapai tidak hilang. Ia menunggumu di check-in pagi berikutnya sebagai usulan, lengkap dengan bacaan Merlin dari obrolan terakhirmu. Kamu tinggal mengonfirmasi, mengubah, atau melepaskan."},{"kind":"aha","text":"Goal yang terbawa tiga pagi berturut-turut bukan goal yang gagal. Ia goal yang mungkin terlalu besar untuk satu hari, atau sebenarnya bukan milikmu. Keduanya layak ditanyakan."},{"kind":"cta","text":"","cta":{"label":"Lihat goal yang terbawa pagi ini"}}]$q$::jsonb, false, 52, '2026-10-01 09:00+07'),
  ($q$J-09$q$, $q$jurnal$q$, $q$Mimpi setinggi langit, goal seukuran hari$q$, $q$souls$q$, 5, $q$AB 2.3 (Reality Meter)$q$, $q$[{"kind":"hook","text":"Mimpi dan goal sering ditulis di kolom yang sama. Padahal keduanya bekerja dengan cara berbeda."},{"kind":"wow","text":"Mimpi boleh setinggi-tingginya dan tidak perlu terukur. Goal harus terukur dan muat dalam hari. Mimpi terwujud dari goal-goal kecil yang tercapai, bukan dari mimpi yang ditulis ulang makin besar."},{"kind":"aha","text":"Satu aturan kecil dari kelas lama yang masih berlaku: jangan ada kata \"tidak\" dalam goal. Otak sulit mengejar ketiadaan. \"Tidak terlambat\" kalah oleh \"tiba pukul tujuh\"."},{"kind":"coba","text":"Periksa tiga goalmu hari ini. Ada kata \"tidak\"? Tulis ulang."},{"kind":"cta","text":"","cta":{"label":"Buka check-in pagi"}}]$q$::jsonb, false, 53, '2026-10-01 09:00+07'),
  ($q$J-10$q$, $q$jurnal$q$, $q$Jurnal tanpa aturan$q$, $q$souls$q$, 5, $q$APP (jurnal, Pemantik) · tradisi expressive writing$q$, $q$[{"kind":"hook","text":"Kamu tidak perlu pandai menulis. Kamu perlu jujur selama dua menit."},{"kind":"wow","text":"Penelitian tentang menulis bebas tentang pengalaman sendiri sudah berlangsung puluhan tahun. Temuannya konsisten: menuliskan apa yang terjadi dan apa yang dirasakan membantu orang memproses, bukan sekadar mengingat. Tata bahasa tidak dinilai."},{"kind":"aha","text":"Jurnal yang baik bukan yang bagus dibaca. Ia yang membuatmu berhenti sejenak sebelum menulis kalimat berikutnya. Kalau macet, ketuk Pemantik."},{"kind":"cta","text":"","cta":{"label":"Tulis jurnal malam ini"}}]$q$::jsonb, false, 54, '2026-10-01 09:00+07'),
  ($q$J-11$q$, $q$jurnal$q$, $q$Kenapa hari bolos tidak dihitung dua kali$q$, $q$souls$q$, 10, $q$APP (logika Realitas Saya dan streak)$q$, $q$[{"kind":"hook","text":"Hari tanpa check-in tidak menurunkan gelombangmu. Itu keputusan desain, bukan kelalaian."},{"kind":"wow","text":"Streak sudah mencatat ketidakhadiranmu. Kalau grafik ikut menghukum, satu hari sakit akan kamu bayar dua kali. Maka pada hari kosong, nilai terakhirmu dibawa, bukan dijatuhkan."},{"kind":"aha","text":"Aplikasi ini membedakan absen dengan mundur. Absen adalah hidup. Mundur adalah hadir tetapi menjauh, dan hanya yang kedua yang layak tercermin di grafik."},{"kind":"cta","text":"","cta":{"label":"Nyalakan kembali streak-mu, kalau sedang padam"}}]$q$::jsonb, false, 55, '2026-10-01 09:00+07'),
  ($q$J-12$q$, $q$jurnal$q$, $q$Momentum: angka yang menggerakkan posisimu$q$, $q$souls$q$, 10, $q$APP (Momentum score)$q$, $q$[{"kind":"hook","text":"Ada satu angka yang tidak pernah ditampilkan besar-besar, tetapi menentukan di mana kamu berdiri di garis Stage 1 ke 3."},{"kind":"wow","text":"Namanya Momentum. Ia menimbang tiga puluh hari terakhir: konsistensi check-in paling berat, lalu arah suasana hatimu, goal yang tercapai, dan refleksi yang ditulis. Bukan satu hari hebat. Tiga puluh hari biasa."},{"kind":"aha","text":"Posisi di garis tidak bisa dibeli dengan satu malam begadang penuh semangat. Ia dibangun dari hari-hari yang tidak istimewa, yang kamu tetap hadir. Itulah momentum: gerak yang terasa ringan karena tidak pernah berhenti."},{"kind":"cta","text":"lihat Stage-mu hari ini.","cta":{"label":"Buka Realitas Saya"}}]$q$::jsonb, false, 56, '2026-10-01 09:00+07'),
  ($q$A-01$q$, $q$audio$q$, $q$Mandi untuk pikiran$q$, $q$free$q$, null, $q$analogi Modwiz · APP (sesi audio)$q$, $q$[{"kind":"hook","text":"Kamu mandi setiap hari tanpa bertanya \"apakah mandi itu bekerja?\"."},{"kind":"wow","text":"Pikiran menerima ribuan masukan sehari: pesan, berita, komentar, kekhawatiran orang lain. Tidak ada yang membersihkannya. Sesi audio sepuluh menit adalah mandi untuk bagian dirimu yang tidak bisa disabuni."},{"kind":"aha","text":"Meditasi bukan tentang mengosongkan pikiran. Ia tentang membilas, supaya yang tersisa adalah milikmu sendiri."},{"kind":"cta","text":"","cta":{"label":"Pilih satu sesi: Priming, Ignite, atau Cosmic"}}]$q$::jsonb, false, 57, '2026-10-09 09:00+07'),
  ($q$A-02$q$, $q$audio$q$, $q$Pikiranmu melantur hampir separuh waktu$q$, $q$free$q$, null, $q$penelitian Killingsworth & Gilbert (2010)$q$, $q$[{"kind":"hook","text":"Dua peneliti mengirim pertanyaan acak ke ribuan ponsel: \"sedang apa, dan sedang memikirkan apa?\""},{"kind":"wow","text":"Hasilnya: sekitar 47 persen waktu, orang memikirkan hal lain dari yang sedang ia kerjakan. Dan saat melantur, mereka melaporkan diri kurang bahagia, apa pun kegiatannya."},{"kind":"aha","text":"Masalahnya bukan hidupmu. Masalahnya kamu jarang hadir di dalamnya. Sesi audio adalah latihan kembali, berulang-ulang, sampai kembali itu menjadi refleks."},{"kind":"cta","text":"","cta":{"label":"Mulai CALM, tiga menit"}}]$q$::jsonb, false, 58, '2026-10-01 09:00+07'),
  ($q$A-03$q$, $q$audio$q$, $q$Delapan minggu yang mengubah otak$q$, $q$free$q$, null, $q$penelitian pencitraan otak Harvard (2011)$q$, $q$[{"kind":"hook","text":"Sebelum 2011, \"meditasi mengubah otak\" adalah klaim. Setelah itu, ia foto."},{"kind":"wow","text":"Peserta berlatih sekitar 27 menit sehari selama delapan minggu. Pemindaian menunjukkan penebalan di wilayah yang mengurus belajar dan ingatan, dan penyusutan di wilayah yang mengurus rasa takut dan stres."},{"kind":"aha","text":"Delapan minggu bukan angka ajaib. Ia angka yang cukup lama untuk tubuh percaya bahwa kamu serius."},{"kind":"cta","text":"delapan minggu adalah 56 hari.","cta":{"label":"Lihat streak-mu"}}]$q$::jsonb, false, 59, '2026-10-01 09:00+07'),
  ($q$A-04$q$, $q$audio$q$, $q$Neurons that fire together wire together$q$, $q$souls$q$, 5, $q$prinsip Hebb (ilmu saraf) · APP (Priming)$q$, $q$[{"kind":"hook","text":"Kalimat ini diajarkan di kelas ilmu saraf mana pun. Ia juga menjelaskan kenapa ritual pagi diulang setiap hari."},{"kind":"wow","text":"Setiap kali dua hal terjadi bersamaan di otak, jalur di antara keduanya menguat. Perasaan tenang yang diulang bersama tiga goalmu, setiap pagi, lama-lama menjadi satu paket: melihat goal, langsung tenang."},{"kind":"aha","text":"Kamu tidak sedang memaksakan pikiran positif. Kamu sedang memasang kabel. Kabel tidak peduli motivasi; ia peduli pengulangan."},{"kind":"cta","text":"","cta":{"label":"Mulai Priming besok pagi, sebelum membuka pesan"}}]$q$::jsonb, false, 60, '2026-10-01 09:00+07'),
  ($q$A-05$q$, $q$audio$q$, $q$Masukan pertama di pagi hari$q$, $q$souls$q$, 5, $q$AB 3.2 · psikologi priming$q$, $q$[{"kind":"hook","text":"Apa hal pertama yang masuk ke kepalamu pagi ini? Kalau jawabannya \"notifikasi\", kamu sudah kalah satu langkah."},{"kind":"wow","text":"Dalam psikologi, apa yang kamu terima lebih dulu memengaruhi cara kamu menafsirkan yang datang setelahnya. Karena itu Modwiz Priming diminta dilakukan sebelum mengecek ponsel, sebelum bicara dengan siapa pun."},{"kind":"aha","text":"Pagi hari ada satu kursi kosong di kepalamu. Kalau kamu tidak mendudukinya, orang lain yang akan."},{"kind":"cta","text":"","cta":{"label":"Atur pengingat Priming lebih awal dari alarm pesanmu"}}]$q$::jsonb, false, 61, '2026-10-01 09:00+07'),
  ($q$A-06$q$, $q$audio$q$, $q$Napas 8-8-8-8: tombol rem tubuhmu$q$, $q$souls$q$, 5, $q$AB 3.2 · fisiologi pernapasan$q$, $q$[{"kind":"hook","text":"Pasukan khusus memakai hitungan empat. Modwiz memakai delapan. Keduanya menekan tombol yang sama."},{"kind":"wow","text":"Tarik delapan hitungan, tahan delapan, buang delapan, kosong delapan. Embusan panjang memberi sinyal pada sistem sarafmu bahwa tidak ada bahaya. Detak melambat, bahu turun, pikiran ikut."},{"kind":"aha","text":"Kamu tidak bisa memerintahkan diri untuk tenang. Tetapi kamu bisa memerintahkan napas, dan tubuh akan menyusul."},{"kind":"coba","text":"Lakukan sekarang, tiga putaran, sebelum lanjut membaca."},{"kind":"cta","text":"hitungan delapan dipandu di dalamnya.","cta":{"label":"Mulai Priming"}}]$q$::jsonb, false, 62, '2026-10-01 09:00+07'),
  ($q$A-07$q$, $q$audio$q$, $q$Kenapa dipandu, bukan hening$q$, $q$souls$q$, 5, $q$APP (sesi audio)$q$, $q$[{"kind":"hook","text":"Meditasi hening sering gagal di menit kedua. Bukan karena kamu tidak berbakat."},{"kind":"wow","text":"Pikiran yang tidak diberi pegangan akan melantur, dan pemula akan menganggap itu kegagalan lalu berhenti. Suara pemandu adalah pegangan: tiap kali kamu lepas, ada kalimat berikutnya yang mengembalikanmu."},{"kind":"aha","text":"Dipandu bukan tingkat pemula. Ia cara memastikan kamu kembali, berkali-kali, dan \"kembali\" itulah latihannya."},{"kind":"cta","text":"","cta":{"label":"Pilih sesi dengan pemandu suara"}}]$q$::jsonb, false, 63, '2026-10-01 09:00+07'),
  ($q$A-08$q$, $q$audio$q$, $q$Tiga ritual, tiga pintu$q$, $q$souls$q$, 5, $q$APP (Priming, Ignite, Cosmic) · AB 2.4$q$, $q$[{"kind":"hook","text":"Kenapa tidak satu sesi saja? Karena pagi, siang, dan malam adalah tiga keadaan tubuh yang berbeda."},{"kind":"wow","text":"Pagi, Priming: bawah sadar paling terbuka, saat yang tepat menanam arah. Siang, Ignite: ada CREATE untuk membuka ide, CALM untuk meredam, READY untuk bersiap. Malam, Cosmic: menutup hari dengan syukur sebelum otak merangkum."},{"kind":"aha","text":"Sesi yang tepat pada jam yang salah terasa seperti obat yang diminum tanpa makan. Pilih pintunya sesuai jamnya."},{"kind":"cta","text":"","cta":{"label":"Lihat ritual yang sedang menunggumu di Home"}}]$q$::jsonb, false, 64, '2026-10-01 09:00+07'),
  ($q$A-09$q$, $q$audio$q$, $q$Syukur sebelum tidur mengubah apa yang otakmu simpan$q$, $q$souls$q$, 5, $q$APP (Cosmic Gratitude) · ilmu tidur dan konsolidasi ingatan$q$, $q$[{"kind":"hook","text":"Tidur bukan jeda. Tidur adalah saat otak memutuskan apa dari hari ini yang layak disimpan."},{"kind":"wow","text":"Ingatan dirapikan saat kamu tidur. Yang kamu pikirkan menjelang tidur mendapat tempat lebih depan dalam antrean. Sesi Cosmic sengaja ditaruh di ujung hari karena itu."},{"kind":"aha","text":"Kamu tidak bisa memilih apa yang terjadi hari ini. Kamu bisa memilih versi mana yang dibawa tidur."},{"kind":"cta","text":"","cta":{"label":"Mulai Cosmic malam ini"}}]$q$::jsonb, false, 65, '2026-10-01 09:00+07'),
  ($q$A-10$q$, $q$audio$q$, $q$Sepuluh menit tiap hari mengalahkan satu jam sesekali$q$, $q$souls$q$, 5, $q$prinsip latihan · APP (streak)$q$, $q$[{"kind":"hook","text":"Satu jam hening pada hari Minggu terasa hebat. Senin pagi, efeknya sudah tidak ada."},{"kind":"wow","text":"Tubuh dan otak merespons frekuensi, bukan durasi. Sepuluh menit yang datang setiap hari memberi sinyal \"ini keadaan normal baru\". Satu jam sebulan sekali memberi sinyal \"ini pengecualian\"."},{"kind":"aha","text":"Pertanyaannya bukan berapa lama kamu bermeditasi. Pertanyaannya berapa hari berturut-turut."},{"kind":"cta","text":"","cta":{"label":"Lihat streak-mu"}}]$q$::jsonb, false, 66, '2026-10-01 09:00+07'),
  ($q$A-11$q$, $q$audio$q$, $q$Awesome Priming: kenapa pemilik gelang menyebutnya "pengaktifan"$q$, $q$souls$q$, 10, $q$AB 3.2 · APP (Awesome Priming, khusus pemilik gelang)$q$, $q$[{"kind":"hook","text":"Ada satu sesi di aplikasi ini yang tertutup untuk umum. Peserta kelasnya punya nama sendiri untuk pengalaman pertama mereka."},{"kind":"wow","text":"Jempol di liontin, tiga kalimat pembuka, napas delapan hitungan, lalu menyelami tiga realita yang ingin dimiliki, dibayangkan sampai terasa nyata. Banyak yang, setelah sesi pertama, langsung menulis ke grup. Bukan diminta. Karena ada yang terasa berpindah."},{"kind":"aha","text":"Kata \"pengaktifan\" tidak dibuat oleh kami. Ia lahir dari orang-orang yang merasakannya. Dan rasa, bukan penjelasan, yang membuat seseorang kembali esok paginya."},{"kind":"cta","text":"","cta":{"label":"Lihat Awesome Bracelet di Courses"}}]$q$::jsonb, false, 67, '2026-10-01 09:00+07'),
  ($q$A-12$q$, $q$audio$q$, $q$Membayangkan tiga realita bukan khayalan, melainkan latihan$q$, $q$souls$q$, 10, $q$AB 3.2 langkah 4 · praktik latihan mental atlet$q$, $q$[{"kind":"hook","text":"Atlet lompat ski melompat puluhan kali di kepalanya sebelum sekali di salju. Mereka tidak menyebutnya berkhayal."},{"kind":"wow","text":"Latihan mental dipakai luas dalam olahraga karena otak mengaktifkan sebagian jalur yang sama saat membayangkan gerakan dengan saat melakukannya. Langkah keempat Priming, menyelami tiga realita sampai terasa, bekerja dengan prinsip yang sama."},{"kind":"aha","text":"Bedanya khayalan dan latihan ada di dua hal: diulang pada jam yang sama, dan diikuti tindakan nyata di siang hari. Tanpa yang kedua, ia tinggal khayalan. Dengan yang kedua, ia gladi bersih."},{"kind":"cta","text":"","cta":{"label":"Mulai Priming, lalu tulis tiga goal yang menyusul bayanganmu"}}]$q$::jsonb, false, 68, '2026-10-01 09:00+07')
on conflict (id) do update set
  category = excluded.category, title = excluded.title, access = excluded.access, price = excluded.price,
  source = excluded.source, slides = excluded.slides, featured = excluded.featured, sort = excluded.sort,
  updated_at = now();
